// IP constraint: no Zelda/Nintendo names, lore, or trademarks in any player-facing text.

export const fishRarities = [
  { name: 'Common',    color: '#b0c4b1', chance: 0.58,  baseCurrency: 10,    pearlValue: 1,  xp: 1  },
  { name: 'Rare',      color: '#4299e1', chance: 0.21,  baseCurrency: 30,    pearlValue: 5,  xp: 3,  luckCoefficient: 1.0 },
  { name: 'Epic',      color: '#c48ce8', chance: 0.09,  baseCurrency: 100,   pearlValue: 10, xp: 6,  luckCoefficient: 1.5 },
  { name: 'Heroic',    color: '#e67e22', chance: 0.065, baseCurrency: 300,   pearlValue: 20, xp: 11, luckCoefficient: 2.0 },
  { name: 'Legendary', color: '#ffd700', chance: 0.035, baseCurrency: 1000,  pearlValue: 32, xp: 18, luckCoefficient: 2.5 },
  { name: 'Mythical',  color: '#f472b6', chance: 0.015, baseCurrency: 3000,  pearlValue: 45, xp: 26, luckCoefficient: 3.0 },
  { name: 'Secret',    color: '#3fd8ec', chance: 0.004, baseCurrency: 10000, pearlValue: 60, xp: 40, luckCoefficient: 4.0 },
  { name: 'Relic', color: '#e8e8f0', chance: 0.001, baseCurrency: 0, pearlValue: 0, xp: 0, luckCoefficient: 0, isSpecialRoll: true }
];

export const SHINY_SELL_MULTIPLIER = 5;

export const locations = [
  {
    id: 'shallows',
    name: 'Mossbrook Shallows',
    unlockLevel: 1,
    unlockCost: 0,
    incomeMultiplier: 1.0,
    accent: '#4fd1a5',
    gradient: 'linear-gradient(180deg, #234a4a 0%, #123028 60%, #0b1f1c 100%)',
    desc: 'A quiet beginner’s pond fed by mountain runoff. The safest place to learn the ropes.'
  },
  {
    id: 'docks',
    name: 'Saltwater Docks',
    unlockLevel: 5,
    unlockCost: 8000,
    incomeMultiplier: 1.15,
    accent: '#4a90d9',
    gradient: 'linear-gradient(180deg, #1b3350 0%, #14283f 60%, #0c1a2b 100%)',
    desc: 'A bustling harbor where salt water meets the river current, drawing bigger catches.'
  },
  {
    id: 'hollow',
    name: 'Willow Hollow Pond',
    unlockLevel: 12,
    unlockCost: 60000,
    incomeMultiplier: 1.35,
    accent: '#a06fd9',
    gradient: 'linear-gradient(180deg, #2c2350 0%, #241a3f 60%, #160f28 100%)',
    desc: 'A secluded, fog-covered pond that holds species you won’t find anywhere else in the cove.'
  },
  {
    id: 'deep',
    name: 'The Blackwater Trench',
    unlockLevel: 20,
    unlockCost: 400000,
    incomeMultiplier: 1.6,
    accent: '#2fd6c8',
    gradient: 'linear-gradient(180deg, #0c1b2e 0%, #071220 60%, #030a12 100%)',
    desc: 'A deep offshore trench where the cove’s rarest, most unusual fish are known to gather.'
  }
];

export function getLocationById(id) {
  return locations.find(l => l.id === id) || locations[0];
}

export const fishCatalogue = [
  { id: 'harborBass', name: 'Harbor Bass', rarity: 'Common', image: 'harbor_bass.png', locations: ['shallows', 'docks'],
    description: 'The everyday catch of the cove: dependable, a little grumpy, and always biting.', minWeight: 0.6, maxWeight: 2.8 },
  { id: 'sturdyBass', name: 'Sturdy Bass', rarity: 'Common', image: 'sturdy_bass.png', locations: ['shallows'],
    description: 'Thick-scaled and stubborn. Anglers say it never backs down from a hook.', minWeight: 0.8, maxWeight: 3.4 },
  { id: 'riverSalmon', name: 'River Salmon', rarity: 'Common', image: 'river_salmon.png', locations: ['docks'],
    description: 'Runs upstream every season without fail. A cove staple for generations.', minWeight: 1.0, maxWeight: 4.2 },
  { id: 'frostfinTrout', name: 'Frostfin Trout', rarity: 'Common', image: 'frostfin_trout.png', locations: ['shallows'],
    description: 'Prefers the coldest pockets of water it can find.', minWeight: 0.5, maxWeight: 2.2 },
  { id: 'emberfinTrout', name: 'Emberfin Trout', rarity: 'Common', image: 'emberfin_trout.png', locations: ['docks'],
    description: 'Its fins flush bright orange when it’s startled off the hook.', minWeight: 0.5, maxWeight: 2.4 },
  { id: 'ironscaleCarp', name: 'Ironscale Carp', rarity: 'Common', image: 'ironscale_carp.png', locations: ['hollow'],
    description: 'Plated scales that clink like coins when it thrashes on the line.', minWeight: 1.2, maxWeight: 5.0 },
  { id: 'ironscalePorgy', name: 'Ironscale Porgy', rarity: 'Common', image: 'ironscale_porgy.png', locations: ['hollow'],
    description: 'A slow, armored grazer of the pond floor.', minWeight: 1.0, maxWeight: 4.0 },

  { id: 'sparkfinTrout', name: 'Sparkfin Trout', rarity: 'Rare', image: 'sparkfin_trout.png', locations: ['shallows', 'docks'],
    description: 'A faint static crackle runs along its fins in the right light.', minWeight: 1.0, maxWeight: 4.5 },
  { id: 'tidalBass', name: 'Tidal Bass', rarity: 'Rare', image: 'tidal_bass.png', locations: ['shallows'],
    description: 'Built for long fights - it will pull your line for minutes before tiring.', minWeight: 1.5, maxWeight: 6.0 },
  { id: 'shadowfinTrout', name: 'Shadowfin Trout', rarity: 'Rare', image: 'shadowfin_trout.png', locations: ['docks'],
    description: 'Almost invisible against the harbor’s dark water.', minWeight: 1.0, maxWeight: 4.0 },
  { id: 'greengill', name: 'Greengill', rarity: 'Rare', image: 'greengill.png', locations: ['docks', 'hollow'],
    description: 'Its gills shimmer a deep emerald when it breaks the surface.', minWeight: 1.2, maxWeight: 5.2 },
  { id: 'toona', name: 'Toona', rarity: 'Rare', image: 'toona.png', locations: ['hollow'],
    description: 'Locals joke it practically jumps into the boat by itself.', minWeight: 2.0, maxWeight: 7.0 },

  { id: 'reekfish', name: 'Reekfish', rarity: 'Epic', image: 'reekfish.png', locations: ['shallows'],
    description: 'You’ll smell it before you see it. Worth the trouble, apparently.', minWeight: 2.0, maxWeight: 8.0 },
  { id: 'millpondCatfish', name: 'Millpond Catfish', rarity: 'Epic', image: 'millpond_catfish.png', locations: ['docks'],
    description: 'A bottom-dweller with whiskers as long as your arm.', minWeight: 3.0, maxWeight: 12.0 },
  { id: 'loovar', name: 'Loovar', rarity: 'Epic', image: 'loovar.png', locations: ['hollow'],
    description: 'No one is entirely sure what a Loovar is. It’s definitely a fish, probably.', minWeight: 2.5, maxWeight: 9.0 },

  { id: 'titanBarracuda', name: 'Titan Barracuda', rarity: 'Heroic', image: 'titan_carp.png', locations: ['hollow'],
    description: 'Rumored to have snapped more than one rod clean in half.', minWeight: 5.0, maxWeight: 18.0 },
  { id: 'titanPorgy', name: 'Titan Porgy', rarity: 'Heroic', image: 'titan_porgy.png', locations: ['docks'],
    description: 'An oversized porgy that dwarfs the harbor’s boats.', minWeight: 4.0, maxWeight: 15.0 },
  { id: 'longtoothPike', name: 'Longtooth Pike', rarity: 'Heroic', image: 'longtooth_pike.png', locations: ['hollow'],
    description: 'An ambush predator with a grin full of needle teeth.', minWeight: 4.5, maxWeight: 16.0 },

  { id: 'moonlitLoach', name: 'Moonlit Loach', rarity: 'Legendary', image: 'moonlit_loach.png', locations: ['shallows'],
    description: 'Only ever seen under a full moon, gliding just beneath the surface.', minWeight: 6.0, maxWeight: 20.0 },
  { id: 'sunfireKoi', name: 'Sunfire Koi', rarity: 'Legendary', image: 'sunfire_koi.png', locations: ['docks'],
    description: 'Its scales look like they’re lit from within by embers.', minWeight: 6.0, maxWeight: 22.0 },
  { id: 'ancientArowana', name: 'Ancient Arowana', rarity: 'Legendary', image: 'ancient_arowana.png', locations: ['deep'],
    description: 'A living fossil pulled from the deepest, oldest part of the trench.', minWeight: 8.0, maxWeight: 26.0 },

  { id: 'wishingFish', name: 'Wishing Fish', rarity: 'Mythical', image: 'wishing_fish.png', locations: ['hollow', 'deep'],
    description: 'Folklore says catching one grants a single stroke of good luck.', minWeight: 0.3, maxWeight: 1.5 },

  { id: 'moonlitLoachJuvenile', name: 'Moonlit Loach (Juvenile)', rarity: 'Secret', image: 'moonlit_loach_juvenile.png', locations: ['deep'],
    description: 'A newborn Moonlit Loach, impossibly rare to hook before it grows.', minWeight: 0.2, maxWeight: 0.9 },

  { id: 'farwaterHerring', name: 'Farwater Herring', rarity: 'Common', image: 'farwater_herring.png', locations: ['shallows', 'docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'bluewaterBass', name: 'Bluewater Bass', rarity: 'Common', image: 'bluewater_bass.png', locations: ['shallows', 'docks'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'longfinTetra', name: 'Longfin Tetra', rarity: 'Common', image: 'longfin_tetra.png', locations: ['shallows'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'sunspotGoldfish', name: 'Sunspot Goldfish', rarity: 'Common', image: 'sunspot_goldfish.png', locations: ['shallows'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'sandbloomTrout', name: 'Sandbloom Trout', rarity: 'Common', image: 'sandbloom_trout.png', locations: ['shallows', 'docks'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'brineButterflyfish', name: 'Brine Butterflyfish', rarity: 'Common', image: 'brine_butterflyfish.png', locations: ['docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'tidewaterButterflyfish', name: 'Tidewater Butterflyfish', rarity: 'Common', image: 'tidewater_butterflyfish.png', locations: ['shallows', 'docks'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'glimmerDamselfish', name: 'Glimmer Damselfish', rarity: 'Common', image: 'glimmer_damselfish.png', locations: ['shallows', 'docks'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'sapphireTang', name: 'Sapphire Tang', rarity: 'Common', image: 'sapphire_tang.png', locations: ['shallows'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'shoalwaterPerch', name: 'Shoalwater Perch', rarity: 'Common', image: 'shoalwater_goldfish.png', locations: ['shallows'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'spindriftPerch', name: 'Spindrift Perch', rarity: 'Common', image: 'spindrift_squirrelfish.png', locations: ['docks'],
    description: 'Common enough near the docks, but its colors never get old.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'paintedTrout', name: 'Painted Trout', rarity: 'Common', image: 'painted_flounder.png', locations: ['shallows'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'coralbandRay', name: 'Coralband Ray', rarity: 'Common', image: 'coralband_damselfish.png', locations: ['shallows'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 2.0, maxWeight: 8.0 },
  { id: 'sunlitButterflyfish', name: 'Sunlit Butterflyfish', rarity: 'Common', image: 'sunlit_butterflyfish.png', locations: ['shallows'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'rippleBluegill', name: 'Ripple Bluegill', rarity: 'Common', image: 'ripple_bluegill.png', locations: ['shallows'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'jadePike', name: 'Jade Pike', rarity: 'Common', image: 'jade_pike.png', locations: ['docks'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'glasswaterMackerel', name: 'Glasswater Mackerel', rarity: 'Common', image: 'glasswater_mackerel.png', locations: ['shallows'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'lowreefHerring', name: 'Lowreef Herring', rarity: 'Common', image: 'lowreef_herring.png', locations: ['shallows'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'pearlDarter', name: 'Pearl Darter', rarity: 'Common', image: 'pearl_darter.png', locations: ['shallows'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'clearwaterMackerel', name: 'Clearwater Mackerel', rarity: 'Common', image: 'clearwater_pearl_clam.png', locations: ['docks'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'turquoiseScallop', name: 'Turquoise Scallop', rarity: 'Common', image: 'turquoise_scallop.png', locations: ['docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'saltmereDarter', name: 'Saltmere Darter', rarity: 'Common', image: 'saltmere_sea_snail.png', locations: ['shallows', 'docks'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'seabreezeSquid', name: 'Seabreeze Squid', rarity: 'Common', image: 'seabreeze_hermit_crab.png', locations: ['shallows'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'dappledJellyfish', name: 'Dappled Jellyfish', rarity: 'Common', image: 'dappled_urchin.png', locations: ['shallows'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'kelpHorseshoeCrab', name: 'Kelp Horseshoe Crab', rarity: 'Common', image: 'kelp_starfish.png', locations: ['docks'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 1.0, maxWeight: 4.0 },
  { id: 'morningtideMussel', name: 'Morningtide Mussel', rarity: 'Common', image: 'morningtide_mussel.png', locations: ['docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'opalScallop', name: 'Opal Scallop', rarity: 'Common', image: 'opal_scallop.png', locations: ['shallows', 'docks'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'warmtideSeaSnail', name: 'Warmtide Sea Snail', rarity: 'Common', image: 'warmtide_sea_snail.png', locations: ['shallows'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'emberMinnows', name: 'Ember Minnows', rarity: 'Common', image: 'ember_minnows.png', locations: ['shallows'],
    description: 'Locals swear its scales run warm - or cold - to the touch, though no one\'s proven it.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'galaxyHerring', name: 'Galaxy Herring', rarity: 'Common', image: 'galaxy_herring.png', locations: ['docks'],
    description: 'Anglers who\'ve hooked one say it made the whole boat glow for a moment.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'backwaterPerch', name: 'Backwater Perch', rarity: 'Common', image: 'backwater_perch.png', locations: ['shallows'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'reedCarp', name: 'Reed Carp', rarity: 'Common', image: 'reed_carp.png', locations: ['docks'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'sandbarPike', name: 'Sandbar Pike', rarity: 'Common', image: 'sandbar_pike.png', locations: ['shallows', 'docks'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'driftwoodGoldfish', name: 'Driftwood Goldfish', rarity: 'Common', image: 'driftwood_goldfish.png', locations: ['shallows'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'streamsideBluegill', name: 'Streamside Bluegill', rarity: 'Common', image: 'streamside_bluegill.png', locations: ['shallows'],
    description: 'A common sight around the cove: steady, reliable, and always willing to bite.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'weirBass', name: 'Weir Bass', rarity: 'Common', image: 'weir_bass.png', locations: ['shallows', 'docks'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'bramblePike', name: 'Bramble Pike', rarity: 'Common', image: 'bramble_pike.png', locations: ['shallows', 'docks'],
    description: 'A common sight around the cove: steady, reliable, and always willing to bite.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'muddyTrout', name: 'Muddy Trout', rarity: 'Common', image: 'muddy_trout.png', locations: ['shallows'],
    description: 'Nothing fancy about this one, but the cove wouldn\'t feel the same without it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'copperCatfish', name: 'Copper Catfish', rarity: 'Common', image: 'copper_catfish.png', locations: ['shallows', 'docks'],
    description: 'You could set your watch by how often these turn up on the line.', minWeight: 3.0, maxWeight: 16.0 },
  { id: 'coveMoorishIdol', name: 'Cove Moorish Idol', rarity: 'Common', image: 'cove_moorish_idol.png', locations: ['shallows', 'docks'],
    description: 'A common sight around the cove: steady, reliable, and always willing to bite.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'brookClownfish', name: 'Brook Clownfish', rarity: 'Common', image: 'brook_clownfish.png', locations: ['docks'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'clayTang', name: 'Clay Tang', rarity: 'Common', image: 'clay_tang.png', locations: ['docks'],
    description: 'You could set your watch by how often these turn up on the line.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'marshTuna', name: 'Marsh Tuna', rarity: 'Common', image: 'marsh_tuna.png', locations: ['shallows', 'docks'],
    description: 'You could set your watch by how often these turn up on the line.', minWeight: 3.0, maxWeight: 16.0 },
  { id: 'dustyMackerel', name: 'Dusty Mackerel', rarity: 'Common', image: 'dusty_mackerel.png', locations: ['shallows', 'docks'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'riverHerring', name: 'River Herring', rarity: 'Common', image: 'river_herring.png', locations: ['shallows', 'docks'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'gravelFlounder', name: 'Gravel Flounder', rarity: 'Common', image: 'gravel_flounder.png', locations: ['docks'],
    description: 'You could set your watch by how often these turn up on the line.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'pebbleshoreCrab', name: 'Pebbleshore Crab', rarity: 'Common', image: 'pebbleshore_crab.png', locations: ['shallows', 'docks'],
    description: 'A small, unassuming find - the kind that fills out a collection more than a coin purse.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'rockpoolShrimp', name: 'Rockpool Shrimp', rarity: 'Common', image: 'rockpool_shrimp.png', locations: ['shallows'],
    description: 'Every kid in the cove has picked one of these out of a tidepool at least once.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'sandyShrimp', name: 'Sandy Shrimp', rarity: 'Common', image: 'sandy_shrimp.png', locations: ['shallows', 'docks'],
    description: 'Found clinging to the rocks and pilings wherever the tide goes out.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'estuaryMussel', name: 'Estuary Mussel', rarity: 'Common', image: 'estuary_mussel.png', locations: ['shallows'],
    description: 'Not much of a fight on the line, but a favorite of anyone exploring the shallows at low tide.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'brackishClam', name: 'Brackish Clam', rarity: 'Common', image: 'brackish_clam.png', locations: ['shallows'],
    description: 'Common along the shoreline, though never quite where you expect it.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'saltflatOyster', name: 'Saltflat Oyster', rarity: 'Common', image: 'saltflat_oyster.png', locations: ['shallows', 'docks'],
    description: 'A small, unassuming find - the kind that fills out a collection more than a coin purse.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'sunwarmedScallop', name: 'Sunwarmed Scallop', rarity: 'Common', image: 'sunwarmed_scallop.png', locations: ['shallows'],
    description: 'Common along the shoreline, though never quite where you expect it.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'tidelineStarfish', name: 'Tideline Starfish', rarity: 'Common', image: 'tideline_starfish.png', locations: ['shallows', 'docks'],
    description: 'Common along the shoreline, though never quite where you expect it.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'coveMinnow', name: 'Cove Minnow', rarity: 'Common', image: 'cove_minnow.png', locations: ['docks'],
    description: 'Not much of a fight on the line, but a favorite of anyone exploring the shallows at low tide.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'lowtideHermitCrab', name: 'Lowtide Hermit Crab', rarity: 'Common', image: 'lowtide_hermit_crab.png', locations: ['shallows', 'docks'],
    description: 'Common along the shoreline, though never quite where you expect it.', minWeight: 0.03, maxWeight: 0.6 },
  { id: 'springfedPerch', name: 'Springfed Perch', rarity: 'Common', image: 'springfed_perch.png', locations: ['shallows', 'docks'],
    description: 'Nothing fancy about this one, but the cove wouldn\'t feel the same without it.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'poolsideShad', name: 'Poolside Shad', rarity: 'Common', image: 'poolside_shad.png', locations: ['docks'],
    description: 'Nothing fancy about this one, but the cove wouldn\'t feel the same without it.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'backcreekBluegill', name: 'Backcreek Bluegill', rarity: 'Common', image: 'backcreek_bluegill.png', locations: ['docks'],
    description: 'Nothing fancy about this one, but the cove wouldn\'t feel the same without it.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'gravelbankBluegill', name: 'Gravelbank Bluegill', rarity: 'Common', image: 'gravelbank_bluegill.png', locations: ['shallows', 'docks'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'rushwaterBass', name: 'Rushwater Bass', rarity: 'Common', image: 'rushwater_bass.png', locations: ['shallows'],
    description: 'You could set your watch by how often these turn up on the line.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'shorelineBass', name: 'Shoreline Bass', rarity: 'Common', image: 'shoreline_bass.png', locations: ['docks'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'lilyPike', name: 'Lily Pike', rarity: 'Common', image: 'lily_pike.png', locations: ['docks'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'marshbendPike', name: 'Marshbend Pike', rarity: 'Common', image: 'marshbend_pike.png', locations: ['docks'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'brackenwoodGar', name: 'Brackenwood Gar', rarity: 'Common', image: 'brackenwood_gar.png', locations: ['shallows', 'docks'],
    description: 'You could set your watch by how often these turn up on the line.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'cattailBass', name: 'Cattail Bass', rarity: 'Common', image: 'cattail_bass.png', locations: ['docks'],
    description: 'Nothing fancy about this one, but the cove wouldn\'t feel the same without it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'farmpondBass', name: 'Farmpond Bass', rarity: 'Common', image: 'farmpond_bass.png', locations: ['shallows'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'creekBass', name: 'Creek Bass', rarity: 'Common', image: 'creek_bass.png', locations: ['shallows', 'docks'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'grassbankMackerel', name: 'Grassbank Mackerel', rarity: 'Common', image: 'grassbank_mackerel.png', locations: ['shallows'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'longpondMackerel', name: 'Longpond Mackerel', rarity: 'Common', image: 'longpond_mackerel.png', locations: ['shallows', 'docks'],
    description: 'Small, quick, and everywhere once you know where to look.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'autumnMackerel', name: 'Autumn Mackerel', rarity: 'Common', image: 'autumn_mackerel.png', locations: ['shallows'],
    description: 'Nothing fancy about this one, but the cove wouldn\'t feel the same without it.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'coolwaterMackerel', name: 'Coolwater Mackerel', rarity: 'Common', image: 'coolwater_mackerel.png', locations: ['shallows', 'docks'],
    description: 'You could set your watch by how often these turn up on the line.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'millraceMackerel', name: 'Millrace Mackerel', rarity: 'Common', image: 'millrace_mackerel.png', locations: ['shallows', 'docks'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'rootboundMackerel', name: 'Rootbound Mackerel', rarity: 'Common', image: 'rootbound_mackerel.png', locations: ['shallows', 'docks'],
    description: 'Nothing fancy about this one, but the cove wouldn\'t feel the same without it.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'claybankBass', name: 'Claybank Bass', rarity: 'Common', image: 'claybank_bass.png', locations: ['docks'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'fallowMackerel', name: 'Fallow Mackerel', rarity: 'Common', image: 'fallow_mackerel.png', locations: ['shallows', 'docks'],
    description: 'Small, quick, and everywhere once you know where to look.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'duckweedShad', name: 'Duckweed Shad', rarity: 'Common', image: 'duckweed_shad.png', locations: ['shallows', 'docks'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'shallowbendBass', name: 'Shallowbend Bass', rarity: 'Common', image: 'shallowbend_bass.png', locations: ['shallows'],
    description: 'You could set your watch by how often these turn up on the line.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'sunwarmedBass', name: 'Sunwarmed Bass', rarity: 'Common', image: 'sunwarmed_bass.png', locations: ['shallows'],
    description: 'Nothing fancy about this one, but the cove wouldn\'t feel the same without it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'cloudyPerch', name: 'Cloudy Perch', rarity: 'Common', image: 'cloudy_perch.png', locations: ['docks'],
    description: 'A common sight around the cove: steady, reliable, and always willing to bite.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'sunkenBass', name: 'Sunken Bass', rarity: 'Common', image: 'sunken_bass.png', locations: ['shallows', 'docks'],
    description: 'Small, quick, and everywhere once you know where to look.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'windbendBass', name: 'Windbend Bass', rarity: 'Common', image: 'windbend_bass.png', locations: ['docks'],
    description: 'Anglers rarely brag about catching one, but everyone\'s tackle box has room for it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'stillwaterBass', name: 'Stillwater Bass', rarity: 'Common', image: 'stillwater_bass.png', locations: ['docks'],
    description: 'A dependable catch for anyone just learning to fish these waters.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'meadowTrout', name: 'Meadow Trout', rarity: 'Common', image: 'meadow_trout.png', locations: ['docks'],
    description: 'A common sight around the cove: steady, reliable, and always willing to bite.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'sedgeSalmon', name: 'Sedge Salmon', rarity: 'Common', image: 'sedge_salmon.png', locations: ['shallows'],
    description: 'Nothing fancy about this one, but the cove wouldn\'t feel the same without it.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'chalkstreamBluegill', name: 'Chalkstream Bluegill', rarity: 'Common', image: 'chalkstream_bluegill.png', locations: ['shallows'],
    description: 'A common sight around the cove: steady, reliable, and always willing to bite.', minWeight: 0.3, maxWeight: 2.5 },
  { id: 'pondBass', name: 'Pond Bass', rarity: 'Common', image: 'pond_bass.png', locations: ['docks'],
    description: 'Small, quick, and everywhere once you know where to look.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'stumpyTrout', name: 'Stumpy Trout', rarity: 'Common', image: 'stumpy_trout.png', locations: ['shallows'],
    description: 'Small, quick, and everywhere once you know where to look.', minWeight: 1.0, maxWeight: 7.0 },
  { id: 'horizonSnapper', name: 'Horizon Snapper', rarity: 'Rare', image: 'horizon_snapper.png', locations: ['hollow'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'wavebreakerSeahorse', name: 'Wavebreaker Seahorse', rarity: 'Rare', image: 'wavebreaker_seahorse.png', locations: ['docks'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'deepwaterFlyingFish', name: 'Deepwater Flying Fish', rarity: 'Rare', image: 'deepwater_flying_fish.png', locations: ['hollow'],
    description: 'Common enough near the docks, but its colors never get old.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'tidecallerLionfish', name: 'Tidecaller Lionfish', rarity: 'Rare', image: 'tidecaller_lionfish.png', locations: ['hollow'],
    description: 'Common enough near the docks, but its colors never get old.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'freewaterPufferfish', name: 'Freewater Pufferfish', rarity: 'Rare', image: 'freewater_pufferfish.png', locations: ['shallows', 'docks'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'bluefinGuitarfish', name: 'Bluefin Guitarfish', rarity: 'Rare', image: 'bluefin_guitarfish.png', locations: ['hollow'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 3.2, maxWeight: 17.9 },
  { id: 'oldwaterBetta', name: 'Oldwater Betta', rarity: 'Rare', image: 'oldwater_betta.png', locations: ['shallows', 'docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'wavecrestScorpionfish', name: 'Wavecrest Scorpionfish', rarity: 'Rare', image: 'wavecrest_scorpionfish.png', locations: ['hollow'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'harborlightEel', name: 'Harborlight Eel', rarity: 'Rare', image: 'harborlight_eel.png', locations: ['shallows', 'docks'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'gildedViperfish', name: 'Gilded Viperfish', rarity: 'Rare', image: 'gilded_viperfish.png', locations: ['docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'pastelLionfish', name: 'Pastel Lionfish', rarity: 'Rare', image: 'pastel_snapper.png', locations: ['hollow'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'calicoMinnows', name: 'Calico Minnows', rarity: 'Rare', image: 'calico_pufferfish.png', locations: ['hollow'],
    description: 'Flashes of color dart through the shallows whenever one of these swims past.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'tangerineLionfish', name: 'Tangerine Lionfish', rarity: 'Rare', image: 'tangerine_lionfish.png', locations: ['docks'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'seaglassSquid', name: 'Seaglass Squid', rarity: 'Rare', image: 'seaglass_squid.png', locations: ['docks'],
    description: 'Common enough near the docks, but its colors never get old.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'reefJellyfish', name: 'Reef Jellyfish', rarity: 'Rare', image: 'reef_jellyfish.png', locations: ['shallows'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'silverlightHermitCrab', name: 'Silverlight Hermit Crab', rarity: 'Rare', image: 'silverlight_hermit_crab.png', locations: ['shallows'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'brightfinUrchin', name: 'Brightfin Urchin', rarity: 'Rare', image: 'brightfin_urchin.png', locations: ['shallows', 'docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'foamStarfish', name: 'Foam Starfish', rarity: 'Rare', image: 'foam_starfish.png', locations: ['docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'frostBass', name: 'Frost Bass', rarity: 'Rare', image: 'frost_bass.png', locations: ['shallows'],
    description: 'Locals swear its scales run warm - or cold - to the touch, though no one\'s proven it.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'astralAngelfish', name: 'Astral Angelfish', rarity: 'Rare', image: 'astral_angelfish.png', locations: ['shallows'],
    description: 'Said to only surface on the clearest, starriest nights over the trench.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'eventideBetta', name: 'Eventide Betta', rarity: 'Rare', image: 'eventide_betta.png', locations: ['docks'],
    description: 'Anglers who\'ve hooked one say it made the whole boat glow for a moment.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'auroraSnapper', name: 'Aurora Snapper', rarity: 'Rare', image: 'aurora_snapper.png', locations: ['docks'],
    description: 'Anglers who\'ve hooked one say it made the whole boat glow for a moment.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'bathyalTriggerfish', name: 'Bathyal Triggerfish', rarity: 'Rare', image: 'bathyal_triggerfish.png', locations: ['docks'],
    description: 'Common enough near the docks, but its colors never get old.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'shadowdeepTriggerfish', name: 'Shadowdeep Triggerfish', rarity: 'Rare', image: 'shadowdeep_triggerfish.png', locations: ['hollow'],
    description: 'Common enough near the docks, but its colors never get old.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'fathomAngelfish', name: 'Fathom Angelfish', rarity: 'Rare', image: 'fathom_angelfish.png', locations: ['docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'duskveilAngelfish', name: 'Duskveil Angelfish', rarity: 'Rare', image: 'duskveil_angelfish.png', locations: ['shallows', 'docks'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'blackwaterAngelfish', name: 'Blackwater Angelfish', rarity: 'Rare', image: 'blackwater_angelfish.png', locations: ['shallows'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'cavernousAngelfish', name: 'Cavernous Angelfish', rarity: 'Rare', image: 'cavernous_angelfish.png', locations: ['docks'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'depthlessTang', name: 'Depthless Tang', rarity: 'Rare', image: 'depthless_tang.png', locations: ['shallows', 'docks'],
    description: 'A lively little catch that puts up more of a fight than its size suggests.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'coldabyssTang', name: 'Coldabyss Tang', rarity: 'Rare', image: 'coldabyss_tang.png', locations: ['shallows', 'docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'shellbedLobster', name: 'Shellbed Lobster', rarity: 'Rare', image: 'shellbed_lobster.png', locations: ['shallows', 'docks'],
    description: 'A small, unassuming find - the kind that fills out a collection more than a coin purse.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'wadingUrchin', name: 'Wading Urchin', rarity: 'Rare', image: 'wading_urchin.png', locations: ['docks'],
    description: 'Found clinging to the rocks and pilings wherever the tide goes out.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'pebblebeachJellyfish', name: 'Pebblebeach Jellyfish', rarity: 'Rare', image: 'pebblebeach_jellyfish.png', locations: ['shallows', 'docks'],
    description: 'Every kid in the cove has picked one of these out of a tidepool at least once.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'saltmarshOctopus', name: 'Saltmarsh Octopus', rarity: 'Rare', image: 'saltmarsh_octopus.png', locations: ['shallows'],
    description: 'Not much of a fight on the line, but a favorite of anyone exploring the shallows at low tide.', minWeight: 1.1, maxWeight: 7.8 },
  { id: 'shorelineSquid', name: 'Shoreline Squid', rarity: 'Rare', image: 'shoreline_squid.png', locations: ['docks'],
    description: 'A small, unassuming find - the kind that fills out a collection more than a coin purse.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'driftlineIsopod', name: 'Driftline Isopod', rarity: 'Rare', image: 'driftline_isopod.png', locations: ['docks'],
    description: 'Not much of a fight on the line, but a favorite of anyone exploring the shallows at low tide.', minWeight: 0.3, maxWeight: 2.8 },
  { id: 'bluecrestSwordfish', name: 'Bluecrest Swordfish', rarity: 'Epic', image: 'bluecrest_swordfish.png', locations: ['hollow'],
    description: 'A catch big enough to need two hands and a strong rod just to bring in.', minWeight: 11.0, maxWeight: 74.4 },
  { id: 'titanicMarlin', name: 'Titanic Marlin', rarity: 'Epic', image: 'titanic_marlin.png', locations: ['docks'],
    description: 'The kind of fish that makes strangers stop and stare when it\'s hauled onto the dock.', minWeight: 11.0, maxWeight: 74.4 },
  { id: 'deeptideMorayEel', name: 'Deeptide Moray Eel', rarity: 'Epic', image: 'deeptide_moray_eel.png', locations: ['docks'],
    description: 'The kind of fish that makes strangers stop and stare when it\'s hauled onto the dock.', minWeight: 3.3, maxWeight: 19.8 },
  { id: 'ironhideMantaRay', name: 'Ironhide Manta Ray', rarity: 'Epic', image: 'ironhide_manta_ray.png', locations: ['docks'],
    description: 'Its size alone is enough to make it the highlight of any angler\'s season.', minWeight: 11.0, maxWeight: 74.4 },
  { id: 'coralAnglerfish', name: 'Coral Anglerfish', rarity: 'Epic', image: 'coral_anglerfish.png', locations: ['docks'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 1.1, maxWeight: 8.7 },
  { id: 'driftlightLobster', name: 'Driftlight Lobster', rarity: 'Epic', image: 'driftlight_lobster.png', locations: ['docks'],
    description: 'Drawn in by bright lures more than most - a favorite among casual anglers.', minWeight: 1.1, maxWeight: 8.7 },
  { id: 'ivoryHerring', name: 'Ivory Herring', rarity: 'Epic', image: 'ivory_horseshoe_crab.png', locations: ['docks'],
    description: 'Small, quick, and always worth a second look before it\'s tossed back or sold.', minWeight: 0.33, maxWeight: 3.1 },
  { id: 'lagoonMussel', name: 'Lagoon Mussel', rarity: 'Epic', image: 'lagoon_mussel.png', locations: ['hollow'],
    description: 'Common enough near the docks, but its colors never get old.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'blazeKoi', name: 'Blaze Koi', rarity: 'Epic', image: 'blaze_koi.png', locations: ['hollow', 'docks'],
    description: 'Its markings look almost unnatural in the right light, like something out of a story.', minWeight: 1.1, maxWeight: 8.7 },
  { id: 'meteorHerring', name: 'Meteor Herring', rarity: 'Epic', image: 'meteor_herring.png', locations: ['docks'],
    description: 'Its scales seem to hold a piece of the night sky, dotted with points of pale light.', minWeight: 0.3, maxWeight: 3.1 },
  { id: 'stardustSeahorse', name: 'Stardust Seahorse', rarity: 'Epic', image: 'stardust_seahorse.png', locations: ['docks'],
    description: 'Its scales seem to hold a piece of the night sky, dotted with points of pale light.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'nebulaMantaRay', name: 'Nebula Manta Ray', rarity: 'Epic', image: 'nebula_manta_ray.png', locations: ['hollow'],
    description: 'Said to only surface on the clearest, starriest nights over the trench.', minWeight: 11.0, maxWeight: 74.4 },
  { id: 'shadowtrenchOctopus', name: 'Shadowtrench Octopus', rarity: 'Epic', image: 'shadowtrench_octopus.png', locations: ['hollow'],
    description: 'Strange enough that most anglers assume it\'s a joke - until they see one for themselves.', minWeight: 1.1, maxWeight: 8.7 },
  { id: 'hollowdeepZebraFish', name: 'Hollowdeep Zebra Fish', rarity: 'Epic', image: 'hollowdeep_zebra_fish.png', locations: ['hollow'],
    description: 'The kind of catch that ends up mounted on a wall rather than sold at the docks.', minWeight: 0.3, maxWeight: 3.1 },
  { id: 'inkwellSquid', name: 'Inkwell Squid', rarity: 'Epic', image: 'inkwell_squid.png', locations: ['hollow', 'docks'],
    description: 'Looks like it belongs in a much older, much stranger ocean.', minWeight: 0.3, maxWeight: 3.1 },
  { id: 'umbralOctopus', name: 'Umbral Octopus', rarity: 'Epic', image: 'umbral_octopus.png', locations: ['hollow'],
    description: 'Even seasoned anglers pause before reeling this one all the way in.', minWeight: 1.1, maxWeight: 8.7 },
  { id: 'trenchOctopus', name: 'Trench Octopus', rarity: 'Epic', image: 'trench_octopus.png', locations: ['hollow', 'docks'],
    description: 'Looks like it belongs in a much older, much stranger ocean.', minWeight: 1.1, maxWeight: 8.7 },
  { id: 'hadalCuttlefish', name: 'Hadal Cuttlefish', rarity: 'Epic', image: 'hadal_cuttlefish.png', locations: ['hollow'],
    description: 'The kind of catch that ends up mounted on a wall rather than sold at the docks.', minWeight: 0.3, maxWeight: 3.1 },
  { id: 'murkveilMandarinfish', name: 'Murkveil Mandarinfish', rarity: 'Epic', image: 'murkveil_mandarinfish.png', locations: ['docks'],
    description: 'Pulled up from depths where sunlight has never once reached.', minWeight: 0.03, maxWeight: 0.7 },
  { id: 'farhorizonHammerheadShark', name: 'Farhorizon Hammerhead Shark', rarity: 'Heroic', image: 'farhorizon_hammerhead_shark.png', locations: ['deep'],
    description: 'One of the cove\'s true giants, spoken about in every dockside fishing story.', minWeight: 11.5, maxWeight: 81.6 },
  { id: 'silverbackMahimahi', name: 'Silverback Mahi-Mahi', rarity: 'Heroic', image: 'silverback_mahi_mahi.png', locations: ['deep'],
    description: 'Its size alone is enough to make it the highlight of any angler\'s season.', minWeight: 3.4, maxWeight: 21.8 },
  { id: 'stormKoi', name: 'Storm Koi', rarity: 'Heroic', image: 'storm_koi.png', locations: ['deep'],
    description: 'Rumored, never confirmed, to leave a faint shimmer on the water where it\'s been.', minWeight: 1.1, maxWeight: 9.5 },
  { id: 'eclipseCatfish', name: 'Eclipse Catfish', rarity: 'Heroic', image: 'eclipse_catfish.png', locations: ['hollow'],
    description: 'Its scales seem to hold a piece of the night sky, dotted with points of pale light.', minWeight: 3.4, maxWeight: 21.8 },
  { id: 'moonveilPufferfish', name: 'Moonveil Pufferfish', rarity: 'Heroic', image: 'moonveil_pufferfish.png', locations: ['hollow', 'deep'],
    description: 'Said to only surface on the clearest, starriest nights over the trench.', minWeight: 1.1, maxWeight: 9.5 },
  { id: 'celestialAnglerfish', name: 'Celestial Anglerfish', rarity: 'Heroic', image: 'celestial_anglerfish.png', locations: ['deep'],
    description: 'Said to only surface on the clearest, starriest nights over the trench.', minWeight: 1.1, maxWeight: 9.5 },
  { id: 'cometLionfish', name: 'Comet Lionfish', rarity: 'Heroic', image: 'comet_lionfish.png', locations: ['deep'],
    description: 'A once-in-a-season catch, worth every hour spent waiting for it.', minWeight: 1.1, maxWeight: 9.5 },
  { id: 'deepfathomAnglerfish', name: 'Deepfathom Anglerfish', rarity: 'Heroic', image: 'deepfathom_anglerfish.png', locations: ['deep'],
    description: 'Pulled up from depths where sunlight has never once reached.', minWeight: 1.1, maxWeight: 9.5 },
  { id: 'grimtideIsopodEel', name: 'Grimtide Isopod Eel', rarity: 'Heroic', image: 'grimtide_isopod_eel.png', locations: ['deep'],
    description: 'Pulled up from depths where sunlight has never once reached.', minWeight: 1.1, maxWeight: 9.5 },
  { id: 'abyssalGiantIsopod', name: 'Abyssal Giant Isopod', rarity: 'Heroic', image: 'abyssal_giant_isopod.png', locations: ['deep'],
    description: 'The kind of catch that ends up mounted on a wall rather than sold at the docks.', minWeight: 1.1, maxWeight: 9.5 },
  { id: 'sunkenMandarinfish', name: 'Sunken Mandarinfish', rarity: 'Heroic', image: 'sunken_mandarinfish.png', locations: ['hollow'],
    description: 'Strange enough that most anglers assume it\'s a joke - until they see one for themselves.', minWeight: 0.03, maxWeight: 0.8 },
  { id: 'vastfinOrca', name: 'Vastfin Orca', rarity: 'Legendary', image: 'vastfin_orca.png', locations: ['hollow'],
    description: 'The kind of fish that makes strangers stop and stare when it\'s hauled onto the dock.', minWeight: 12.0, maxWeight: 88.8 },
  { id: 'endlessWhaleShark', name: 'Endless Whale Shark', rarity: 'Legendary', image: 'endless_whale_shark.png', locations: ['shallows'],
    description: 'Its size alone is enough to make it the highlight of any angler\'s season.', minWeight: 12.0, maxWeight: 88.8 },
  { id: 'starlitShark', name: 'Starlit Shark', rarity: 'Legendary', image: 'starlit_shark.png', locations: ['docks'],
    description: 'A once-in-a-season catch, worth every hour spent waiting for it.', minWeight: 3.6, maxWeight: 23.7 },
  { id: 'novaMarlin', name: 'Nova Marlin', rarity: 'Legendary', image: 'nova_marlin.png', locations: ['deep'],
    description: 'No one can explain the faint shimmer that trails behind it - least of all the anglers who catch one.', minWeight: 12.0, maxWeight: 88.8 },
  { id: 'faralightNautilus', name: 'Faralight Nautilus', rarity: 'Legendary', image: 'faralight_nautilus.png', locations: ['hollow'],
    description: 'The kind of catch that ends up mounted on a wall rather than sold at the docks.', minWeight: 0.4, maxWeight: 3.7 },
  { id: 'obsidianNautilus', name: 'Obsidian Nautilus', rarity: 'Legendary', image: 'obsidian_nautilus.png', locations: ['docks'],
    description: 'Looks like it belongs in a much older, much stranger ocean.', minWeight: 0.4, maxWeight: 3.7 },
  { id: 'sableSeaDragon', name: 'Sable Sea Dragon', rarity: 'Legendary', image: 'sable_sea_dragon.png', locations: ['docks'],
    description: 'Pulled up from depths where sunlight has never once reached.', minWeight: 0.4, maxWeight: 3.7 },
  { id: 'voidfinSeaDragon', name: 'Voidfin Sea Dragon', rarity: 'Legendary', image: 'voidfin_sea_dragon.png', locations: ['shallows'],
    description: 'Pulled up from depths where sunlight has never once reached.', minWeight: 0.4, maxWeight: 3.7 },
  { id: 'openwaterNarwhal', name: 'Openwater Narwhal', rarity: 'Mythical', image: 'openwater_narwhal.png', locations: ['hollow', 'deep'],
    description: 'Its size alone is enough to make it the highlight of any angler\'s season.', minWeight: 12.5, maxWeight: 96.0 },
  { id: 'greatfinDolphin', name: 'Greatfin Dolphin', rarity: 'Mythical', image: 'greatfin_dolphin.png', locations: ['deep'],
    description: 'One of the cove\'s true giants, spoken about in every dockside fishing story.', minWeight: 12.5, maxWeight: 96.0 },
  { id: 'thunderShark', name: 'Thunder Shark', rarity: 'Mythical', image: 'thunder_shark.png', locations: ['deep'],
    description: 'Locals swear its scales run warm - or cold - to the touch, though no one\'s proven it.', minWeight: 3.8, maxWeight: 25.6 },
  { id: 'ashenStingray', name: 'Ashen Stingray', rarity: 'Mythical', image: 'ashen_stingray.png', locations: ['deep'],
    description: 'Locals swear its scales run warm - or cold - to the touch, though no one\'s proven it.', minWeight: 3.8, maxWeight: 25.6 },
  { id: 'midnightShark', name: 'Midnight Shark', rarity: 'Mythical', image: 'midnight_shark.png', locations: ['hollow', 'deep'],
    description: 'No one can explain the faint shimmer that trails behind it - least of all the anglers who catch one.', minWeight: 3.8, maxWeight: 25.6 },
  { id: 'starfallJellyfish', name: 'Starfall Jellyfish', rarity: 'Mythical', image: 'starfall_jellyfish.png', locations: ['hollow', 'deep'],
    description: 'No one can explain the faint shimmer that trails behind it - least of all the anglers who catch one.', minWeight: 0.4, maxWeight: 4.0 },
  { id: 'lunarDolphin', name: 'Lunar Dolphin', rarity: 'Secret', image: 'lunar_dolphin.png', locations: ['hollow', 'deep'],
    description: 'No one can explain the faint shimmer that trails behind it - least of all the anglers who catch one.', minWeight: 13.0, maxWeight: 103.2 },
];

export function getFishById(id) {
  return fishCatalogue.find(f => f.id === id);
}

export const junkCatalogue = [
  { id: 'rustyCan', name: 'Rusty Tin Can', image: 'junk_rusty_can.png',
    description: "Someone's lunch, a long time ago." },
  { id: 'brokenBottle', name: 'Broken Bottle', image: 'junk_broken_bottle.png',
    description: 'Careful: the edges are still sharp.' },
  { id: 'tangledSeaweed', name: 'Tangled Seaweed', image: 'junk_tangled_seaweed.png',
    description: 'Wraps around the hook every single time.' },
  { id: 'waterloggedBoot', name: 'Waterlogged Boot', image: 'junk_waterlogged_boot.png',
    description: "Only one. The other's still out there somewhere." },
  { id: 'ballOfTwine', name: 'Ball of Old Twine', image: 'junk_ball_of_twine.png',
    description: 'More knot than string at this point.' },
  { id: 'fishSkeleton', name: 'Fish Skeleton', image: 'junk_fish_skeleton.png',
    description: 'Something got here first.' },
  { id: 'mossyRock', name: 'Mossy Rock', image: 'junk_mossy_rock.png',
    description: 'Heavier than it looks. Also, a rock.' },
  { id: 'tornNet', name: 'Torn Fishing Net', image: 'junk_torn_net.png',
    description: "Someone else's bad day, from a while back." },
  { id: 'oldTire', name: 'Old Tire', image: 'junk_old_tire.png',
    description: 'How does it even end up out here?' },
  { id: 'plasticBag', name: 'Plastic Bag', image: 'junk_plastic_bag.png',
    description: "Worth fishing out, even if it's not worth anything." }
];

export function getFishPoolForLocation(locationId, rarityName) {
  const pool = fishCatalogue.filter(f => f.rarity === rarityName && f.locations.includes(locationId));
  if (pool.length > 0) return pool;
  return fishCatalogue.filter(f => f.rarity === rarityName);
}

// Legacy (pre-rename) fish/rarity names -> current fish ids; these keys are load-bearing for save migration.
export const LEGACY_NAME_TO_ID = {
  'Hyrule Bass': 'harborBass',
  'Hearty Bass': 'sturdyBass',
  'Hearty Salmon': 'riverSalmon',
  'Chillfin Trout': 'frostfinTrout',
  'Sizzlefin Trout': 'emberfinTrout',
  'Armored Carp': 'ironscaleCarp',
  'Armored Porgy': 'ironscalePorgy',
  'Voltfin Trout': 'sparkfinTrout',
  'Staminoka Bass': 'tidalBass',
  'Stealthfin Trout': 'shadowfinTrout',
  'Greengill': 'greengill',
  'Toona': 'toona',
  'Reekfish': 'reekfish',
  'Ordon Catfish': 'millpondCatfish',
  'Loovar': 'loovar',
  'Mighty Carp': 'titanBarracuda',
  'Mighty Porgy': 'titanPorgy',
  'Hylian Pike': 'longtoothPike',
  'Hylian Loach': 'moonlitLoach',
  'Sanke Carp': 'sunfireKoi',
  'Ancient Arowana': 'ancientArowana',
  'Fairy Fish': 'wishingFish',
  'Hylian Loach (Baby)': 'moonlitLoachJuvenile'
};

// Save-format: relic ownership keys on `id` and stores type/value per entry — id/type/value must never change; name/description/image are display-only.
export const relicShards = [
  { id: 1, name: 'Tidegrip Gauntlet', type: 'reelSpeed', value: 0.05, color: '#4fd1a5', image: 'relic_tidegrip_gauntlet.png', description: 'A barnacled iron glove that never lets a line slip.' },
  { id: 2, name: "Seer's Glass",      type: 'luck',      value: 0.05, color: '#4a90d9', image: 'relic_seers_glass.png',      description: 'A clouded crystal that shows where the fish are biting.' },
  { id: 3, name: 'Tome of Tides',     type: 'reelSpeed', value: 0.05, color: '#a06fd9', image: 'relic_tome_of_tides.png',    description: 'Runes for every current. The pages turn themselves.' },
  { id: 4, name: 'Emberheart Orb',    type: 'luck',      value: 0.05, color: '#e67e22', image: 'relic_emberheart_orb.png',   description: 'A flame that burns underwater and draws rare things near.' },
  { id: 5, name: 'Maelstrom Seal',    type: 'reelSpeed', value: 0.05, color: '#ffd700', image: 'relic_maelstrom_seal.png',   description: 'A stone-ringed whirlpool that spins your reel along.' },
  { id: 6, name: 'Prism Sigil',       type: 'luck',      value: 0.05, color: '#e84393', image: 'relic_prism_sigil.png',      description: 'Its colours shift with the tide, and so does fortune.' },
  { id: 7, name: 'Drowned Crown',     type: 'reelSpeed', value: 0.05, color: '#00bcd4', image: 'relic_drowned_crown.png',    description: 'Once worn by a sunken king who never waited on a bite.' },
  { id: 8, name: "Mariner's Ring",    type: 'luck',      value: 0.05, color: '#ffcc00', image: 'relic_mariners_ring.png',    description: "A sailor's keepsake, still warm with old luck." }
];

